name: CI Dashboard

# Se ejecuta al hacer push o pull request a master
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # 1. Clonar el repositorio
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Configurar Python
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # Cambia a tu versión de Python si es necesario

    # 3. Instalar dependencias
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. Ejecutar pruebas (si existen)
    - name: Run tests
      run: |
        if [ -f "tests/test_main.py" ]; then
          pytest tests/ --junitxml=report.xml
        else
          echo "No test files found, skipping"
        fi

    # 5. Guardar reporte de pruebas
    - name: Upload test report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: report.xml
